### ISSUE TITLE
Add/delete quest to/from questlog

### ISSUE THREAD

**Issue by jonasoo98** [heyloft/maraudersmap#53] opened 2022-10-04 12:22 UTC
### Description:
When adding a quest there should be some kind of dialog wether you want to accept or deny a quest.

**Comment by mathiazom** [comment] 2022-11-03 08:01
Semi-duplicate of #18, also deleting from quest log ("abandon") will not be supported at this point.

**Closed by mathiazom** 2022-11-03 08:01 UTC
Labels: user story, Frontend, Backend
